name: DeepLeague2
channels:
- menpo
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.8.6=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- ffmpeg=3.1.3=0
- pip:
  - bleach==1.5.0
  - cycler==0.10.0
  - enum34==1.1.10
  - h5py==2.10.0
  - html5lib==0.9999999
  - keras==2.8.0
  - markdown==3.3.6
  - matplotlib==3.5.1
  - numpy==1.22.3
  - opencv-python==4.4.5.64
  - pillow==9.0.1
  - protobuf==3.19.4
  - pyparsing==3.0.7
  - python-dateutil==2.8.2
  - pytz==2017.3
  - pyyaml==3.12
  - scipy==1.4.1
  - six==1.16.0
  - tensorflow==2.2.0
  - tensorflow-tensorboard==1.5.1
  - werkzeug==2.0.3
  - youtube-dl==2021.12.17
